services:
  api-python:
    build: .
    image: ghcr.io/keil-enzo/devsecops-tp1-api:${API_TAG:-local}
    user: "65532:65532"
    read_only: true
    tmpfs:
      - /tmp:size=16m,mode=1777
    cap_drop: [ALL]
    security_opt:
      - no-new-privileges:true
    mem_limit: 256m
    cpus: 0.5
    pids_limit: 100
    restart: unless-stopped
    ports:
      - "${API_PORT:-5000}:5000"
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: ${POSTGRES_DB:?POSTGRES_DB manquant dans .env}
      DB_USER: ${POSTGRES_USER:?POSTGRES_USER manquant dans .env}
      DB_PASSWORD: ${POSTGRES_PASSWORD:?POSTGRES_PASSWORD manquant dans .env}
    networks:
      - frontend
      - backend
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test:
        - CMD
        - /usr/bin/python3
        - -c
        - "import urllib.request,sys; sys.exit(0 if urllib.request.urlopen('http://127.0.0.1:5000/health', timeout=3).status == 200 else 1)"
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s

  db:
    image: cgr.dev/chainguard/postgres:latest@sha256:0c4eaf6cb9bd65337d834f5ebfe79add4312ee2125ab584bf1fbc071abc6bb8f
    user: "70:70"
    read_only: true
    tmpfs:
      - /tmp:size=16m,mode=1777
      - /var/run/postgresql:size=1m,uid=70,gid=70
    cap_drop: [ALL]
    security_opt:
      - no-new-privileges:true
    mem_limit: 512m
    cpus: 1
    pids_limit: 200
    shm_size: 128m
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER:?POSTGRES_USER manquant dans .env}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:?POSTGRES_PASSWORD manquant dans .env}
      POSTGRES_DB: ${POSTGRES_DB:?POSTGRES_DB manquant dans .env}
      PGDATA: /var/lib/postgresql/data
    volumes:
      - db-data:/var/lib/postgresql
    networks:
      - backend
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${POSTGRES_USER}", "-d", "${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

networks:
  frontend:
  backend:
    internal: true

volumes:
  db-data:
